import crypto from 'node:crypto';
function b64url(buf){return buf.toString('base64url')} function fromB64url(s){return Buffer.from(s,'base64url')}
export function deriveKey(secret){if(!secret||secret.length<32)throw new Error('DATA_ENCRYPTION_KEY must be at least 32 characters');return crypto.createHash('sha256').update(secret,'utf8').digest()}
export function encryptText(plaintext,secret){if(plaintext==null)return null;const key=deriveKey(secret),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),ciphertext=Buffer.concat([cipher.update(String(plaintext),'utf8'),cipher.final()]),tag=cipher.getAuthTag();return `v1.${b64url(iv)}.${b64url(tag)}.${b64url(ciphertext)}`}
export function decryptText(value,secret){if(!value)return null;const [v,ivs,tags,cts]=String(value).split('.');if(v!=='v1'||!ivs||!tags||!cts)throw new Error('Invalid encrypted value');const d=crypto.createDecipheriv('aes-256-gcm',deriveKey(secret),fromB64url(ivs));d.setAuthTag(fromB64url(tags));return Buffer.concat([d.update(fromB64url(cts)),d.final()]).toString('utf8')}
export function stableCustomerRef(identifier,secret){if(!identifier)throw new Error('Missing customer identifier');if(!secret||secret.length<24)throw new Error('CUSTOMER_REF_SECRET must be at least 24 characters');return 'wa_'+crypto.createHmac('sha256',secret).update(String(identifier)).digest('hex').slice(0,32)}
export function verifyYCloudSignature(rawBody,header,secret,nowSeconds=Math.floor(Date.now()/1000),toleranceSeconds=300){if(!secret||!header)return false;const parts=Object.fromEntries(String(header).split(',').map(p=>p.trim().split('='))),ts=Number(parts.t),sig=parts.s;if(!Number.isFinite(ts)||!sig||Math.abs(nowSeconds-ts)>toleranceSeconds)return false;const expected=crypto.createHmac('sha256',secret).update(`${ts}.${rawBody}`).digest('hex'),a=Buffer.from(expected,'hex');let b;try{b=Buffer.from(sig,'hex')}catch{return false}return a.length===b.length&&crypto.timingSafeEqual(a,b)}
export function signSession(payload,secret){const data=b64url(Buffer.from(JSON.stringify(payload),'utf8')),sig=crypto.createHmac('sha256',secret).update(data).digest('base64url');return `${data}.${sig}`}
export function verifySession(token,secret){if(!token)return null;const [data,sig]=String(token).split('.');if(!data||!sig)return null;const expected=crypto.createHmac('sha256',secret).update(data).digest('base64url'),a=Buffer.from(expected),b=Buffer.from(sig);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const payload=JSON.parse(Buffer.from(data,'base64url').toString('utf8'));return payload.exp&&Date.now()<=payload.exp?payload:null}
