import pg from 'pg';
import {encryptText,decryptText} from './crypto.mjs';
const {Pool}=pg;
export function createDb(connectionString,encryptionKey){if(!connectionString)throw new Error('DATABASE_URL is required');const pool=new Pool({connectionString,ssl:connectionString.includes('localhost')?false:{rejectUnauthorized:false},max:10});return{
pool,
async migrate(){await pool.query(`
create table if not exists wa_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
create table if not exists wa_conversations(id uuid primary key,customer_ref text not null unique,external_user_id text,phone_enc text,source_context text not null default 'ORGANIC_WHATSAPP',owner text not null default 'AI',state text not null default 'OPEN',primary_intent text,risk_flags jsonb not null default '[]'::jsonb,control_state text not null default 'NONE',last_response_id text,last_activity_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists wa_messages(id bigserial primary key,conversation_id uuid not null references wa_conversations(id) on delete cascade,provider_message_id text unique,direction text not null,message_type text not null,body_enc text,status text,sent_at timestamptz,created_at timestamptz not null default now());
create index if not exists wa_messages_conv_created on wa_messages(conversation_id,created_at desc);
create table if not exists wa_events(event_id text primary key,event_type text not null,received_at timestamptz not null default now(),processed_at timestamptz,state text not null default 'RECEIVED',error text);
create table if not exists wa_escalations(id bigserial primary key,conversation_id uuid not null references wa_conversations(id) on delete cascade,reason text not null,flags jsonb not null default '[]'::jsonb,status text not null default 'OPEN',created_at timestamptz not null default now(),resolved_at timestamptz);
create table if not exists wa_audit(id bigserial primary key,conversation_id uuid,action text not null,actor text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());`);},
async ping(){const r=await pool.query('select 1 as ok');return r.rows[0].ok===1},
async claimEvent(id,type){const r=await pool.query('insert into wa_events(event_id,event_type) values($1,$2) on conflict do nothing returning event_id',[id,type]);return r.rowCount===1},
async finishEvent(id,state='PROCESSED',error=null){await pool.query('update wa_events set processed_at=now(),state=$2,error=$3 where event_id=$1',[id,state,error])},
async getSetting(key,fallback=null){const r=await pool.query('select value from wa_settings where key=$1',[key]);return r.rows[0]?.value??fallback},
async setSetting(key,value){await pool.query('insert into wa_settings(key,value) values($1,$2::jsonb) on conflict(key) do update set value=excluded.value,updated_at=now()',[key,JSON.stringify(value)])},
async getOrCreateConversation({id,customerRef,externalUserId,phone}){const phoneEnc=phone?encryptText(phone,encryptionKey):null;const r=await pool.query(`insert into wa_conversations(id,customer_ref,external_user_id,phone_enc) values($1,$2,$3,$4) on conflict(customer_ref) do update set external_user_id=coalesce(excluded.external_user_id,wa_conversations.external_user_id),phone_enc=coalesce(excluded.phone_enc,wa_conversations.phone_enc),last_activity_at=now(),updated_at=now() returning *`,[id,customerRef,externalUserId||null,phoneEnc]);return r.rows[0]},
async addMessage({conversationId,providerMessageId,direction,type,body,status,sentAt}){const enc=body?encryptText(body,encryptionKey):null;await pool.query(`insert into wa_messages(conversation_id,provider_message_id,direction,message_type,body_enc,status,sent_at) values($1,$2,$3,$4,$5,$6,$7) on conflict(provider_message_id) do nothing`,[conversationId,providerMessageId||null,direction,type,enc,status||null,sentAt||null]);await pool.query('update wa_conversations set last_activity_at=now(),updated_at=now() where id=$1',[conversationId])},
async recentMessages(conversationId,limit=10){const r=await pool.query('select direction,message_type,body_enc,created_at from wa_messages where conversation_id=$1 order by created_at desc limit $2',[conversationId,Math.min(limit,20)]);return r.rows.reverse().map(x=>({...x,body:x.body_enc?decryptText(x.body_enc,encryptionKey):null,body_enc:undefined}))},
async updateConversation(id,patch){const allowed=['owner','state','primary_intent','risk_flags','control_state','last_response_id'],entries=Object.entries(patch).filter(([k])=>allowed.includes(k));if(!entries.length)return;const sets=[],vals=[id];let i=2;for(const[k,v]of entries){sets.push(`${k}=$${i++}${k==='risk_flags'?'::jsonb':''}`);vals.push(k==='risk_flags'?JSON.stringify(v):v)}await pool.query(`update wa_conversations set ${sets.join(',')},updated_at=now() where id=$1`,vals)},
async escalate(conversationId,reason,flags=[]){await pool.query('insert into wa_escalations(conversation_id,reason,flags) values($1,$2,$3::jsonb)',[conversationId,reason,JSON.stringify(flags)])},
async audit(conversationId,action,actor,details={}){await pool.query('insert into wa_audit(conversation_id,action,actor,details) values($1,$2,$3,$4::jsonb)',[conversationId||null,action,actor,JSON.stringify(details)])},
async summary(){const[c,e,m]=await Promise.all([pool.query("select count(*)::int total,count(*) filter(where owner='HUMAN')::int human_owned,count(*) filter(where state='OPEN')::int open from wa_conversations"),pool.query("select count(*)::int open from wa_escalations where status='OPEN'"),pool.query("select count(*)::int last_24h from wa_messages where created_at>now()-interval '24 hours'")]);return{...c.rows[0],escalations:e.rows[0].open,messages_24h:m.rows[0].last_24h}},
async listConversations(limit=100){const r=await pool.query(`select c.id,c.customer_ref,c.owner,c.state,c.primary_intent,c.risk_flags,c.control_state,c.last_activity_at,(select count(*) from wa_escalations e where e.conversation_id=c.id and e.status='OPEN')::int open_escalations from wa_conversations c order by last_activity_at desc limit $1`,[Math.min(limit,200)]);return r.rows},
async getConversation(id){const r=await pool.query('select * from wa_conversations where id=$1',[id]);if(!r.rows[0])return null;const x=r.rows[0];return{...x,phone:x.phone_enc?decryptText(x.phone_enc,encryptionKey):null,phone_enc:undefined}},
async resolveEscalations(id){await pool.query("update wa_escalations set status='RESOLVED',resolved_at=now() where conversation_id=$1 and status='OPEN'",[id])},
async cleanup(retentionDays=30){const r=await pool.query("update wa_messages set body_enc=null where body_enc is not null and created_at < now()-($1::text || ' days')::interval",[String(retentionDays)]);return r.rowCount}
}};
