const SAFETY=/\b(swelling|difficulty breathing|can'?t breathe|shortness of breath|anaphyl|severe burn|blister|eye swelling|faint|emergency|hospital|dermatologist diagnosed|prescription|tretinoin|isotretinoin)\b/i;
const PAYMENT=/\b(mpesa|m-pesa|paid|payment|charged|deducted|transaction|stk|pay again|duplicate payment)\b/i;
const AUTH=/\b(fake|counterfeit|authentic|original|genuine|authenticity)\b/i;
const SERVICE=/\b(refund|return|replacement|wrong item|missing item|damaged|leaking|broken|complaint)\b/i;
const PRIVACY=/\b(delete my data|privacy|unsubscribe|opt out|stop marketing|my data)\b/i;
export function preflightRisk(text=''){const flags=[];if(SAFETY.test(text))flags.push('SAFETY_REVIEW');if(PAYMENT.test(text))flags.push('PAYMENT_REVIEW');if(AUTH.test(text))flags.push('AUTHENTICITY_REVIEW');if(SERVICE.test(text))flags.push('SERVICE_RECOVERY');if(PRIVACY.test(text))flags.push('PRIVACY_REVIEW');return{flags,blocking:flags.length>0}}
export function safeEscalationReply(flags){if(flags.includes('SAFETY_REVIEW'))return "Thanks for telling us. I’m flagging this for human review rather than guessing. Please stop using the product for now if it is causing a significant reaction. If symptoms are severe, rapidly worsening, or affecting breathing or the eyes, seek urgent medical care.";if(flags.includes('PAYMENT_REVIEW'))return "Thanks — I’m flagging this payment for verification. Please don’t pay again until we confirm the first transaction, so we don’t risk a duplicate payment.";if(flags.includes('AUTHENTICITY_REVIEW'))return "Thanks for raising this. I can’t confirm authenticity from a chat or packaging description alone, so I’m flagging it for verification before we give you a definite answer.";if(flags.includes('SERVICE_RECOVERY'))return "Thanks for letting us know. I’m opening this for human service review so we can verify what happened and resolve the issue correctly.";if(flags.includes('PRIVACY_REVIEW'))return "I’ve flagged this as a privacy or communication-preference request so it can be handled correctly rather than treated as an ordinary support message.";return "Thanks for your message. I’ve flagged this for the team to review."}
export function qaCustomerReply(text=''){const reasons=[];if(!text.trim())reasons.push('EMPTY');if(text.length>1800)reasons.push('TOO_LONG');if(/\b(here is a reply|ready to send|draft:|option 1|internal enum|reason code)\b/i.test(text))reasons.push('META_TEXT');if(/\b(definitely authentic|definitely fake|guaranteed|cures? acne|treats? eczema|safe for everyone)\b/i.test(text))reasons.push('UNSUPPORTED_CERTAINTY');if(/\b(pay again|make another payment)\b/i.test(text)&&/\b(mpesa|m-pesa|payment|paid|charged|deducted)\b/i.test(text))reasons.push('REPAY_RISK');return{pass:reasons.length===0,reasons}}
export function isClosedNow(hoursConfig,date=new Date()){if(!hoursConfig||hoursConfig.configured!==true)return{closed:false,configured:false,reason:'SCHEDULE_NOT_CONFIGURED'};const timezone=hoursConfig.timezone||'Africa/Nairobi',parts=new Intl.DateTimeFormat('en-US',{timeZone:timezone,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(date),day=parts.find(p=>p.type==='weekday')?.value,hh=Number(parts.find(p=>p.type==='hour')?.value),mm=Number(parts.find(p=>p.type==='minute')?.value),minute=hh*60+mm,rule=hoursConfig.week?.[day];if(!rule||rule.closed===true)return{closed:true,configured:true,reason:'CLOSED_DAY'};const[sh,sm]=String(rule.open).split(':').map(Number),[eh,em]=String(rule.close).split(':').map(Number),open=sh*60+sm,close=eh*60+em;return{closed:minute<open||minute>=close,configured:true,reason:'HOURS'}}
export function shouldAutoSend({mode,owner,riskBlocking,hoursResult}){if(owner!=='AI')return{send:false,reason:'HUMAN_OWNED'};if(riskBlocking)return{send:false,reason:'RISK_BLOCK'};if(mode==='HUMAN_ONLY'||mode==='SHADOW')return{send:false,reason:mode};if(mode==='AI_ALWAYS')return{send:true,reason:'AI_ALWAYS'};if(mode==='AFTER_HOURS'){if(!hoursResult.configured)return{send:false,reason:'SCHEDULE_NOT_CONFIGURED'};return hoursResult.closed?{send:true,reason:'CLOSED'}:{send:false,reason:'OPEN'}}return{send:false,reason:'UNKNOWN_MODE'}}
